mindmap
  root((План))
    {{Основы Gradle}}
        (Основные<br/>понятия)
        (Структура проекта)
        (Работа с зависимостями)
        (Многомодульность)
        (Build логика)
    {{Детальный разбор Gradle}}
        (Gradle Wrapped)
        (Gradle Daemon)
        (ЖЦ Gradle проекта)
        (Gradle Tasks)
        (Gradle Plugins)
    {{Практика}}
        (Напишем плагин)

