---
title: Gradle Daemon
---
flowchart LR
    gradlew([./gradlew build])


    gradlew --x run("Run Gradle process")

    client("Gradle
    client run")
    gradlew --> client
    daemon("Gradle
    daemon run")
    client -- local socket --> daemon
    daemon -- local socket --> client
