flowchart BT
    app[(app)]
    core(core)

    feature1 & feature2 --> app
    core --> feature1
    core --> feature2
    model --> core
%%    model --> app
%%    core --> app


    subgraph Features
        feature1(feature1)
        feature2(feature2)
    end
